### ISSUE TITLE
Build #10 was broken

### ISSUE THREAD

**Issue by Ritzlgrmft** [Ritzlgrmft/ionic-configuration-viewer#1]
```
> ionic-configuration-viewer@0.0.0-development compile /home/travis/build/Ritzlgrmft/ionic-configuration-viewer
> ngc -p tsconfig.ngc.json
Error: Error at /home/travis/build/Ritzlgrmft/ionic-configuration-viewer/node_modules/@types/jasmine/index.d.ts:39:38: A parameter initializer is only allowed in a function or constructor implementation.
Error at /home/travis/build/Ritzlgrmft/ionic-configuration-viewer/node_modules/@types/jasmine/index.d.ts:39:46: Cannot find name 'keyof'.
Error at /home/travis/build/Ritzlgrmft/ionic-configuration-viewer/node_modules/@types/jasmine/index.d.ts:39:52: '=' expected.
    at check (/home/travis/build/Ritzlgrmft/ionic-configuration-viewer/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/home/travis/build/Ritzlgrmft/ionic-configuration-viewer/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /home/travis/build/Ritzlgrmft/ionic-configuration-viewer/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
```

**Comment by Ritzlgrmft** [comment]
The newest version of `@types/jasmine` requires typescript 2.1 which breaks the build. Therefore version `2.5.41` has to be fixed.
