### ISSUE TITLE
Build #11 was broken

### ISSUE THREAD

**Issue by Ritzlgrmft** [Ritzlgrmft/ionic-configuration-viewer#2]
```
> ionic-configuration-viewer@0.0.0-development lint /home/travis/build/Ritzlgrmft/ionic-configuration-viewer
> tslint --project tsconfig.ngc.json --config tslint.typecheck.json --format verbose --type-check --exclude "**/*.spec.ts"
/home/travis/build/Ritzlgrmft/ionic-configuration-viewer/node_modules/tslint/lib/runner.js:118
            throw error;
            ^
TypeError: Cannot read property 'full' of undefined
    at Object.<anonymous> (/home/travis/build/Ritzlgrmft/ionic-configuration-viewer/node_modules/codelyzer/util/ngVersion.js:4:58)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/Ritzlgrmft/ionic-configuration-viewer/node_modules/codelyzer/angular/templates/templateParser.js:5:19)
    at Module._compile (module.js:570:32)
```

**Comment by Ritzlgrmft** [comment]
Happens probably because dependency `codelyzer@~2.0.0-beta.4` installed `codelyzer@2.0.1`, which needs a too-new version of angular. Fixing of `codelyzer`'s version should fix the issue.
